### ISSUE TITLE
Deployment failed, because sillyname module is not able to install

### ISSUE THREAD

**Issue by arianf** [crewapp/crewapp#131]
Deploy Error needs to be fixed

```
[stderr]npm http GET https://registry.npmjs.org/body-parser
[stderr]npm http GET https://registry.npmjs.org/sillyname
[stderr]npm http GET https://registry.npmjs.org/bcrypt-nodejs/0.0.3
[stderr]npm http GET https://registry.npmjs.org/express
[stderr]npm http GET https://registry.npmjs.org/mysql
[stderr]npm http GET https://registry.npmjs.org/sequelize
[stderr]npm http GET https://registry.npmjs.org/socket.io
[stderr]npm http 304 https://registry.npmjs.org/mysql
[stderr]npm http 304 https://registry.npmjs.org/express
[stderr]npm http 304 https://registry.npmjs.org/body-parser
[stderr]npm http 304 https://registry.npmjs.org/socket.io
[stderr]npm http 304 https://registry.npmjs.org/sillyname
[stderr]npm ERR! Error: No compatible version found: sillyname@'crewapp/sillyname'
[stderr]npm ERR! Valid install targets:
[stderr]npm ERR! ["0.0.1","0.0.2","0.0.3"]
[stderr]npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
[stderr]npm ERR!     at /usr/share/npm/lib/cache.js:638:10
[stderr]npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
[stderr]npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
[stderr]npm ERR!     at Object.oncomplete (fs.js:107:15)
[stderr]npm ERR! If you need help, you may report this log at:
[stderr]npm ERR!     <http://github.com/isaacs/npm/issues>
[stderr]npm ERR! or email it to:
[stderr]npm ERR!     <npm-@googlegroups.com>
[stderr]
[stderr]npm ERR! System Linux 3.13.0-44-generic
[stderr]npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
[stderr]npm ERR! cwd /home/ubuntu/public/server
[stderr]npm ERR! node -v v0.10.25
[stderr]npm ERR! npm -v 1.3.10
[stderr]npm http 304 https://registry.npmjs.org/bcrypt-nodejs/0.0.3
[stderr]npm http 304 https://registry.npmjs.org/sequelize
[stderr]npm ERR! 
[stderr]npm ERR! Additional logging details can be found in:
[stderr]npm ERR!     /home/ubuntu/public/server/npm-debug.log
[stderr]npm ERR! not ok code 0
```

**Comment by arianf** [comment]
This has been fixed
